version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: innovix
      POSTGRES_PASSWORD: root

  db_test:
    image: postgres:latest
    container_name: postgres_db_test
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: innovix_test
      POSTGRES_PASSWORD: root

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - db_test
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/innovix"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "root"
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
